### ISSUE TITLE
When looking at submissions in Nebula.  The eyeball should link to the product

### ISSUE THREAD

**Issue by soundwarrior** [cherryaudio/store-issues#26]
### Description: The eyeball icon should link to the product, and the product name should link to the product, not the product submission 'view' since you can see that in the product.
![submission-page](https://user-images.githubusercontent.com/679120/110843005-a9a99f00-825c-11eb-846c-a10e39196c99.png)

**Comment by andymnewhouse** [comment]
The eyeball takes you to the submission view, because that's where you can make and see the comments.

![screencapture-store-cherryaudio-nebula-submissions-1877-2021-03-12-11_35_00](https://user-images.githubusercontent.com/6541180/110977034-433d8300-8327-11eb-8b54-e38e38913f95.png)

Maybe it would be useful to switch the order of the preview and comments?

**Comment by andymnewhouse** [comment]
Or on nebula I could not show the preview at all.

**Comment by andymnewhouse** [comment]
Fixed in 3.5.10 - I linked the name, but did not change the link of the eye.
