### ISSUE TITLE
Preview when uploading a manufacturer background is not correct

### ISSUE THREAD

**Issue by tstone** [cherryaudio/store-issues#31]
### Description:
When uploading a manufacturer background image, even if the image is the recommended 1500x750 size, the preview is not shown at the correct aspect ratio.  I haven't yet testing saving the image to see if it shows up incorrectly on the web page itself, as I don't want to get in a state where I can't undo that change.

## Steps to reproduce

- Open Nebula
- Settings
- Web page
- Upload a "Background" that is exactly 1500x750
- "Preview" area does not render correctly

**Comment by andymnewhouse** [comment]
Yeah I just reproduced it, there's a similar issue with the product's icon preview. What's happening is the library used for handling uploads gives you a "preview_url" but that preview url is a thumbnail it creates instead of the actual uploaded file. 

If you save it does look correct, I just tested it with Cherry Audio.

**Comment by andymnewhouse** [comment]
Fixed in 3.5.19
