### ISSUE TITLE
Tool tip on resend email when inviting team members

### ISSUE THREAD

**Issue by tstone** [cherryaudio/store-issues#33]
### Description:

When inviting a team member, and there is a pending invite active, it's not clear what the triangle icon is because it has no tool tip. I realized after I started writing this ticket that the header has a tooltip, but that's not as obvious. Feels like the tool tip should be on the clickable button itself.

**Comment by andymnewhouse** [comment]
The triangle is supposed to look like a paper plane, but I could update that icon to better indicate email. 

I didn't want to put the tooltips on every button because I get annoyed by them and feel like they get in the way, but if you and others feel strongly about it I will gladly make the switch.

**Comment by andymnewhouse** [comment]
I changed the icon to a more traditional mail icon, I hope this is helpful.

<img width="185" alt="Screen Shot 2021-03-30 at 3 42 40 PM" src="https://user-images.githubusercontent.com/6541180/113054030-92304880-916e-11eb-99df-6b3694d56e20.png">
