### ISSUE TITLE
Show all currently on-sale products

### ISSUE THREAD

**Issue by techenby** [cherryaudio/store-issues#76]
### Description:

Have a page similar to modules/bundles/search page that has all currently on-sale products.

**Comment by tstone** [comment]
I know you've been looking for feedback on managing promotions. Something that might be interesting which relates to this is if Cherry Audio actually created promotions that developers could add products too. For example, the 1000 Module promotion is happening now, and that has probably manifested in a dozen or so developers creating their own promotions. What if Cherry Audio set that up, and it was visible to developers to add products to, but not to change the dates or whatever around? With that in place, it would be possible to dynamically generate a page just for a sale, so that e.g. a user could go to the 1000 Module Sale page, and see all the modules for just that sale.

**Comment by andymnewhouse** [comment]
Ooh I like this.

**Comment by scottmetoyer** [comment]
Added in 3.9.6.
