### ISSUE TITLE
Bundles:  Server Error 500 on leaving "Crossed Out Price/Regular Price" field blank while saving

### ISSUE THREAD

**Issue by AndreasFrankeSL** [cherryaudio/store-issues#77]
Browser Report: https://www.whatsmybrowser.org/b/_XXXXX_

### Description:
If you leave the "Crossed Out Price/Regular Price" field blank and try to let the system calculate the "Crossed Out Price" and try to save your settings, the server always throws an error 500. Calculation does not work.

### Detailed steps to reproduce the issue:
Open Nebula, create a bundle, add products, set the bundle price, leave "Crossed Out Price/Regular Price" field blank and try to save.

**Comment by tstone** [comment]
Was just about to file this same bug. Seeing it as well.

**Comment by andymnewhouse** [comment]
I believe I may have fixed this?

**Comment by tstone** [comment]
I just re-tested this now. I'm not getting a 500 error, but I might be unclear on what the intended behavior should be. Do modules _require_ a Crossed out price? What I often do is try and delete the crossed out price because to me there's the regular prices and a sale price, and I'm not sure what the crossed our price is. However based on how it's working right now, I'm wondering if the way that I'm thinking about it isn't supported. It seems to be that a crossed our price is required.

**Comment by andymnewhouse** [comment]
So there's a few different price concepts in the app, so let me do my best to explain.

**Product's price:** the base amount that a person will pay if no other conditions are met (upgrades/sales)
**Product's regular price or crossed out price:** the amount that will be crossed out, this is a static amount that will never be charged to the user. This can give the illusion that something is discounted. The regular price/crossed out price shouldn't be required, and if isn't listed shouldn't appear _except_ in the case of a bundle where if the regular price/crossed out price is empty the regular price/crossed out price will be a sum of the individual prices.
**Sale price:** the amount that a person will pay during the duration of a sale, this does not change the amount of the product in the database.

**Current price:** the calcula amount that the person will pay, this takes account upgrades and sales.

**Comment by AndreasFrankeSL** [comment]
I can only see "Price" and "Crossed Out Price/Regular Price" in the store. "Sale price" and "Current price" doesn't exist in the store.

![chrome_pe22HFLz26](https://user-images.githubusercontent.com/61082272/122809559-8ddb7d80-d2ce-11eb-8027-fa80fc6bf963.jpg)

**Comment by andymnewhouse** [comment]
Correct, because the "current price" is calculated on the fly for that particular user. 

For example:

- If the user isn't logged in and there is not a sale, the user will see the price for the product. 
- If the user isn't logged in and there is a sale, the user will see the sale price for the product.
- If the user is logged in and there is not a sale or upgrades the user will see the price for the product.
- If the user is logged in and there are upgrades that they qualify for they will see the price for the upgrade.
- If the user is logged in and there is a sale, and no conditions on the sale they will see the sale price
- If the user is logged in and there is a sale, and there are conditions on the sale that they qualify for they will see the discounted sale price
- If the product is a bundle, the user is logged in, they own part of the bundle, and automatic discounts are turned on, they will see the calculated discount.

I hope this all makes sense. And If I can make it clearer here, or in the app please let me know :)
