### ISSUE TITLE
Server Error 500 on "Submit for Approval" 

### ISSUE THREAD

**Issue by tstone** [cherryaudio/store-issues#85]
### Description:
WHEN there is an existing approved store submission for a product
AND that submission has not been published
AND "Submit for Approval" is clicked on a subsequent build
THEN the dashboard returns a Server Error 500

The context here is I had put in a build for approval. Later that day I received feedback from a beta tester and further refined a feature. The store submission was approved, but I created a subsequent build and did another round of feedback. Instead of releasing the approved build and doing another build with a minor change, I decided to just release it all together. Submitting the latest build for approval, even with a pending approved submission is how I encountered this.

It looks like after the 500, it took the latest build out of beta too.

Probably not the most common of use cases, but I figured I'd mention it.

**Comment by techenby** [comment]
Thank you for mentioning this! I really appreciate all your bugs reports.

Honestly I think this 500 is because our email provider doesn't think my email exists... which it does 🤷🏻

I've changed the code to only send our notification to our QA guy.

FYI: Submitting a module would also take it out of beta... not sure if that's the desired behavior but that's what happens currently.

**Comment by techenby** [comment]
Fixed in 3.6.5
